export const nameMap = {
  "/admin-2083/login": "Login",
  "/dashboard": "Dashboard Admin",  
  "/dashboard/manage-news": "Manage News",
  "/dashboard/manage-news/add": "Add News",
  "/dashboard/manage-news/edit/:id": "Edit News",
  "/dashboard/manage-events": "Manage Event",
  "/dashboard/manage-events/add": "Add Event",
  "/dashboard/manage-events/edit/:id": "Edit Event",
  "/dashboard/manage-publications": "Manage Publication",
  "/dashboard/manage-publications/add": "Add Publication",
  "/dashboard/manage-publications/edit/:id": "Edit Publication",
  "/dashboard/manage-members": "Manage Member",
  "/dashboard/manage-members/add": "Add Member",
  "/dashboard/manage-members/edit/:id": "Edit Member",
};
