export const nameMap = {
  "/login": "Login",
  "/dashboard": "Dashboard Admin",  
  "/dashboard/manage-news": "Manage News",
  "/dashboard/manage-news/add": "Add News",
  "/dashboard/manage-news/edit": "Edit News",
  "/dashboard/manage-event": "Manage Event",
  "/dashboard/manage-event/add": "Add Event",
  "/dashboard/manage-article/:articleId": "Edit Article",
  "/dashboard/manage-admin": "Manage Admin",
  "/dashboard/manage-admin/add": "Add Admin",
  "/dashboard/manage-admin/:adminId": "Edit Admin",
  "/dashboard/manage-event": "Manage Event",
  "/dashboard/manage-event/add": "Add Event",
  "/dashboard/manage-event/edit": "Edit Event",
};
