export const nameMap = {
  "/admin-2083/login": "Login",
  "/dashboard": "Dashboard Admin",  
  "/dashboard/manage-news": "Manage News",
  "/dashboard/manage-news/add": "Add News",
  "/dashboard/manage-news/edit/:id": "Edit News",
  "/dashboard/manage-event": "Manage Event",
  "/dashboard/manage-event/add": "Add Event",
  "/dashboard/manage-event/edit/:id": "Edit Event",
  "/dashboard/manage-publication": "Manage Publication",
  "/dashboard/manage-publication/add": "Add Publication",
  "/dashboard/manage-publication/edit/:id": "Edit Publication",
  "/dashboard/manage-member": "Manage Member",
  "/dashboard/manage-member/add": "Add Member",
  "/dashboard/manage-member/edit/:id": "Edit Member",
};
